### ISSUE TITLE
Request: Example for MQTT + SSL 

### ISSUE THREAD

**Issue by cBashTN** [telit/IoT-AppZone-SampleApps#5]
Thank you for all these helpful samples!
We have hundreds of ME310G1 in use (NB-IoT) which send data to FTP servers, and we plan to use >1000 per year. So far so good.

Now, customers really want to steer from FTP to MQTT. And all want to use MQTT with certificates for AWS or Azure.

Do you have a (MAIN_UART) sample for the use of MQTT with SSL certifcates? Some customers want to use AWS Cloud with (x.509) certificates.
I'm thinking of a combination of
https://github.com/telit/IoT-AppZone-SampleApps/tree/master/ME310G1-ME910G1-ML865G1/AppZoneSampleApps-MAIN_UART/MQTT
and
https://github.com/telit/IoT-AppZone-SampleApps/tree/master/ME310G1-ME910G1-ML865G1/AppZoneSampleApps-MAIN_UART/TLS_SSL_CLIENT 

To use AWS loT Core one needs:
- A public "CA File" (eg. AmazonRootCA1.pem)
- A "Client Certificate File" (eg. b094f34211-private.pem.key)
- A "Client Key File" (eg. b094f34211-certificate.pem.crt)
- A Broker Address ( eg. demown3vba7lh-ats.iot.eu-central-1.amazonaws.com)
- A Broker Port: 8883
- A Client Id: eg. MyDevice1234
- Optionally some Proxy stuff

And all above certificates/information have to be changeable or updatable in some way (Firmware change, programmed directly or with a transmission if possible)

**Comment by fabiopi-tlt** [comment]
Hello and thanks for your feedback!
The application you linked https://github.com/telit/IoT-AppZone-SampleApps/tree/master/ME310G1-ME910G1-ML865G1/AppZoneSampleApps-MAIN_UART/MQTT already supports SSL (you will need a firmware version 30.00.xx9 to use it properly). To use it, yoyìu will have to set https://github.com/telit/IoT-AppZone-SampleApps/blob/master/ME310G1-ME910G1-ML865G1/AppZoneSampleApps-MAIN_UART/MQTT/src/mqtt_demo.c according to your needs.
In detail, change the values of 

```c
/* SSL */
#define CACERTFILE        ""   /* Root CA file path in module filesystem (if needed) */
#define CLIENTCERTFILE    ""   /* Client certificate file path in module filesystem (if needed) */
#define CLIENTKEYFILE     ""   /* Client private key file path in module filesystem (if needed) */


#define USER_SSL_AUTH      M2MB_SSL_NO_AUTH
```
in order to define them to your certificate paths in the module filesystem

for example, on ME910, you could do:

```c
/* SSL */
#define CACERTFILE        "/mod/rootCA.cer"   /* Root CA file path in module filesystem (if needed) */
#define CLIENTCERTFILE    "/mod/cert.cer"   /* Client certificate file path in module filesystem (if needed) */
#define CLIENTKEYFILE     "/mod/cert.key"   /* Client private key file path in module filesystem (if needed) */


#define USER_SSL_AUTH      M2MB_SSL_SERVER_CLIENT_AUTH 
```
you will then have to store the certificates in the device with the `AT#M2MWRITE` command, for example
`AT#M2MWRITE="/mod/rootCA.cer",<size_in_bytes>`

you will then need to send the file content in RAW mode with a terminal after the module sends the prompt.


about your last question, you could have a file with configuration info locally stored, and use a routine in IoT core to push a new file and a restart, then the app will parse the file at the very beginning and use the new configuration. Does it sound sensible to you?

Regards

**Comment by cBashTN** [comment]
Thank you @fabiopi-tlt !

I think you gave us good information to start with a proof-of-concept.  

```AT#M2MWRITE``` was new to us.
